.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. oggnalive_qt test_oggnalive_qt
clean: FORCE
	$(MAKE) -C .. oggnalive_qt_clean test_oggnalive_qt_clean
check: FORCE
	$(MAKE) -C .. test_oggnalive_qt_check
oggnalive-qt oggnalive-qt.exe: FORCE
	 $(MAKE) -C .. oggnalive_qt
apk: FORCE
	$(MAKE) -C .. oggnalive_qt_apk
